algorithm: began

data_dir: "./data"
num_workers: 2

latent_dim: 128

batch_size: 64
epochs: 50

optimizer:
  name: adam
  lr: 0.0001
  betas: [0.5, 0.999]

gamma: 0.5
lambda_k: 0.001

lr_decay_patience: 12
lr_decay_factor: 0.5
lr_decay_threshold: 0.0001