algorithm: naive_gan

d_steps: 1
g_steps: 1

data_dir: "./data"
num_workers: 2

latent_dim: 100

optimizer: 
  name: adam
  lr: 0.0002
  betas: [0.5, 0.999]
  momentum: 0.9

# optimizer:
#   name: sgd
#   lr: 0.01
#   momentum: 0.9

momentum: 0.5
batch_size: 64
epochs: 20
